version: "1.0"

services:
  db:
    image: mysql
    container_name: WeShareUs-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    restart: always
  back:
    build:
      context: ./WeShareUs-back
      dockerfile: ../Dockerfile.back
    ports:
      - "4000:3000"
    environment:
      - SERVER_PORT=3000
      - MYSQL_HOST=db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=WeShareUs
      - MYSQL_PORT=3306
    depends_on:
      - db
    restart: always
    volumes:
      - ./WeShareUs-back/src:/WeShareUs-back/src
  front:
    build:
      context: ./WeShareUs-front
      dockerfile: ../Dockerfile.front
    ports:
      - "3000:3000"
    depends_on:
      - db
      - back
    restart: always
    volumes:
      - ./WeShareUs-front/src:/WeShareUs-front/src
  back-office:
    build:
      context: ./WeShareUs-back-office
      dockerfile: ../Dockerfile.back-office
    ports:
      - "7727:3000"
    depends_on:
      - db
      - back
    volumes:
      - ./WeShareUs-back-office/src:/WeShareUs-back-office/src